services:
  database:
    image: mysql
    container_name: database-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # mysql -h 127.0.0.1 -p
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      TZ: "Asia/Singapore"
    ports:
      # Expose the service to enable the end user to verify when the tables are populated
      - "3306:3306"
    restart: "no"
    volumes:
      # This directory is used to initialise the database. Use read-only mount
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - "bilby"

  ner:
    build:
      context: ./ner_service/ # Directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: ner-service-container
    restart: "no"
    environment:
      TZ: "Asia/Singapore"
    networks:
      - "bilby"

networks:
  # Use this network for service discovery by among containers
  # As per docker documentation, a prefix based on the parent directory name is added to the network name
  # https://docs.docker.com/compose/how-tos/networking/
  bilby:
    driver: bridge
