services:
  database:
    image: postgres:latest
    container_name: database-container
    environment:
      # psql --host localhost --port 5432 --username $USER --dbname $MYSQL_DATABASE
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Singapore"
    ports:
      # Expose the service to enable the end user to verify when the tables are populated
      - "5432:5432"
    restart: "no"
    networks:
      - "bilby"
networks:
  # Use this network for service discovery by among containers
  # As per docker documentation, a prefix based on the parent directory name is added to the network name
  # https://docs.docker.com/compose/how-tos/networking/
  bilby:
    driver: bridge
