# This file is responsible for deploying the Named Entity Recogniser service, together with the replicaset
apiVersion: v1
kind: Namespace
metadata:
  name: bilby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner
  namespace: bilby
  labels:
    app: ner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ner
  template:
    metadata:
      labels:
        app: ner
    spec:
      containers:
        - name: ner-container
          image: barmanroys/ner-service # The public image name from my Dockerhub
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: TZ

---
apiVersion: v1
kind: Service
metadata:
  name: ner # This is the service name which other containers use to access the database. Defined in the configmap
  namespace: bilby
  labels:
    app: ner
spec:
  ports:
    # Defined in the ASGI service definition
    - port: 8081
      targetPort: 8081
      name: ner
  selector:
    app: ner
  type: ClusterIP
